window.addEventListener("load",function(){
    let eid ="24877x300x250x4219x_ADSLOT1"; let eidi = eid+"i";
    let ifm = document.createElement("iframe");
        ifm.frameBorder=0;ifm.scrolling= "no";ifm.width= "300";ifm.height= "250";ifm.id=eidi;
        document.getElementById(eid).style.maxWidth = eid.split("x")[1] + "px";
        document.getElementById(eid).style.maxHeight = eid.split("x")[2] + "px";
    document.getElementById(eid).appendChild(ifm);
    let doc = document.getElementById(eidi).contentWindow.document;
    doc.write("<head><script type='text/javascript' src='https://cdn.pixfuture.com/djax_elastic.js'> <\/script><script type='text/javascript' src='https://cdn.pixfuture.com/auc.js'></script><\/head><div id=\""+eid+"\"></div><style>html,body{border: 0px;margin: 0px;padding: 0px;}</style>");
    var qymur = '';
qymur += "<"+"script type=\"text/javascript\">\n";
qymur += "var file_url = \"//served-by.pixfuture.com/www/headerbid/library/\";\n";
qymur += "var t = 3;\n";
qymur += "var tout = 2000;\n";
qymur += "var site_url = \"//served-by.pixfuture.com/www/headerbid/library/\";\n";
qymur += "var org_site_url = \"//served-by.pixfuture.com/www/headerbid/library/\";\n";
qymur += "var int = new Array();\n";
qymur += "var pbjs = pbjs || {};\n";
qymur += "pbjs.que = pbjs.que || [];\n";
qymur += "var che = \"300\";\n";
qymur += "var sz = [\"24877x300x250x4219x_ADSLOT1\"];\n";
qymur += "var bz = [\"banner\"];\n";
qymur += "int[0]={\"24877x300x250x4219x_ADSLOT1\":{\"url\":\"\",\"is_house\":1,\"cpm\":0,\"floor_price\":0,\"width\":\"300\",\"height\":\"250\",\"code\":\"4219\",\"zoneid\":\"24877\",\"adUnitCode\":\"24877x300x250x4219x_ADSLOT1\",\"type\":\"house\",\"third_share\":\"70\",\"int_share\":\"70\",\"passback\":\"<"+"script async src=\\\"https:\\/\\/pagead2.googlesyndication.com\\/pagead\\/js\\/adsbygoogle.js\\\"><"+"\\/script> <"+"!-- Square --> <"+"ins class=\\\"adsbygoogle\\\" style=\\\"display:block\\\" data-ad-client=\\\"ca-pub-3732773600888178\\\" data-ad-slot=\\\"5246390033\\\" data-ad-format=\\\"auto\\\" data-full-width-responsive=\\\"true\\\"><"+"\\/ins> <"+"script> (adsbygoogle = window.adsbygoogle || []).push({}); <"+"\\/script>\",\"campaignId\":null,\"bannerId\":null}};\n";
qymur += "var ttcbi = [\n";
qymur += "/*header-bidding-bidders*/\n";
qymur += "{\n";
qymur += "code:\"24877x300x250x4219x_ADSLOT1\",\n";
qymur += "mediaTypes: {banner: { sizes:[300,250]}},\n";
qymur += "bids: [{bidder : \"aol\",params: {\"placement\": \"3344884\",\"network\": \"9834\"}},{bidder : \"appnexus\",params: {\"keywords\": { \"myKeyword\": \"education,icons,free,download,png,svg\",\"myOtherKeyword\": [\'education\',\'icons\',\'free\',\'download\',\'png\',\'svg\']},\"placementId\": 14620345}},{bidder : \"conversant\",params: {\"site_id\": \"202603\"}},{bidder : \"openx\",params: {\"customParams\": { \"myKeyword\": \"education,icons,free,download,png,svg\",\"myOtherKeyword\": [\'education\',\'icons\',\'free\',\'download\',\'png\',\'svg\']},\"delDomain\": \"pixfuture2-d.openx.net\",\"unit\": \"540580840\"}},{bidder : \"pulsepoint\",params: {\"ct\": 686540,\"cp\": 561987,\"cf\": \"300x250\"}},{bidder : \"smartadserver\",params: {\"target\": \"education=education|icons=icons|free=free|download=download|png=png|svg=svg\",\"formatId\": 88672,\"pageId\": 1240155,\"siteId\": \"354470\"}},{bidder : \"pubmatic\",params: {\"dctr\": \"education=education|icons=icons|free=free|download=download|png=png|svg=svg\",\"adSlot\": \"2069654\",\"publisherId\": \"158127\",\"kadfloor\": \"0.1\"}},{bidder : \"33across\",params: {\"siteId\": \"azC7qard4r6OkMaKlId8sQ\",\"productId\": \"siab\"}},{bidder : \"synacormedia\",params: {\"seatId\": \"pixfuture\",\"placementId\": \"84884\",\"bidfloor\": 0.1}},{bidder : \"improvedigital\",params: {\"placementId\": 22254128,\"bidFloor\": 0.1}}]\n";
qymur += "}];\n";
qymur += "pbjs.que.push(function(){\n";
qymur += "pbjs.setConfig({\n";
qymur += "userSync: {\n";
qymur += "filterSettings: {\n";
qymur += "iframe: {\n";
qymur += "bidders: \"*\",\n";
qymur += "filter: \"include\"\n";
qymur += "}\n";
qymur += "},\n";
qymur += "syncsPerBidder: 0,\n";
qymur += "syncDelay: 1000\n";
qymur += "},\n";
qymur += "schain: {\n";
qymur += "validation: \"strict\",\n";
qymur += "config: {\n";
qymur += "ver:\"1.0\",\n";
qymur += "complete: 1,\n";
qymur += "nodes: [\n";
qymur += "{\n";
qymur += "asi:\"pixfuture.com\",\n";
qymur += "sid:\"4219\",\n";
qymur += "hp:1\n";
qymur += "}\n";
qymur += "]\n";
qymur += "}\n";
qymur += "},\n";
qymur += "consentManagement: {\n";
qymur += "gdpr: {\n";
qymur += "cmpApi: \"iab\",\n";
qymur += "timeout: 100,\n";
qymur += "allowAuctionWithoutConsent: true\n";
qymur += "},\n";
qymur += "usp: {\n";
qymur += "timeout: 100 // US Privacy timeout 100ms\n";
qymur += "}\n";
qymur += "},pubcid: {expInterval: 525600}       })\n";
qymur += "pbjs.requestBids({\n";
qymur += "adUnits:ttcbi,\n";
qymur += "bidsBackHandler: function(bidResponses) {\n";
qymur += "try {\n";
qymur += "//console.log(dome(ttcbi));\n";
qymur += "dome(ttcbi, false);\n";
qymur += "} catch (e) {\n";
qymur += "console.log(e);\n";
qymur += "console.log(\"retry sending request!!!!!!!\");\n";
qymur += "setTimeout(function(){\n";
qymur += "dome(ttcbi, false);\n";
qymur += "}, 300);\n";
qymur += "}\n";
qymur += "},\n";
qymur += "timeout: 2000,\n";
qymur += "});\n";
qymur += "});\n";
qymur += "var zone_id         = 24877;\n";
qymur += "function loadScript(url, callback) {\n";
qymur += "var script = document.createElement(\"script\")\n";
qymur += "script.type = \"text/javascript\";\n";
qymur += "if (script.readyState) {\n";
qymur += "script.onreadystatechange = function() {\n";
qymur += "if (script.readyState == \"loaded\" || script.readyState == \"complete\") {\n";
qymur += "script.onreadystatechange = null;\n";
qymur += "callback()\n";
qymur += "}\n";
qymur += "}\n";
qymur += "} else {\n";
qymur += "script.onload = function() {\n";
qymur += "callback()\n";
qymur += "}\n";
qymur += "}\n";
qymur += "script.src = url;\n";
qymur += "document.getElementsByTagName(\"head\")[0].appendChild(script)\n";
qymur += "}\n";
qymur += "<"+"/script>\n";
doc.write(qymur);
doc.close();});