window.addEventListener("load",function(){
    let eid ="24880x728x90x4219x_ADSLOT1"; let eidi = eid+"i";
    let ifm = document.createElement("iframe");
        ifm.frameBorder=0;ifm.scrolling= "no";ifm.width= "728";ifm.height= "90";ifm.id=eidi;
        document.getElementById(eid).style.maxWidth = eid.split("x")[1] + "px";
        document.getElementById(eid).style.maxHeight = eid.split("x")[2] + "px";
    document.getElementById(eid).appendChild(ifm);
    let doc = document.getElementById(eidi).contentWindow.document;
    doc.write("<head><script type='text/javascript' src='https://cdn.pixfuture.com/djax_elastic.js'> <\/script><script type='text/javascript' src='https://cdn.pixfuture.com/auc.js'></script><\/head><div id=\""+eid+"\"></div><style>html,body{border: 0px;margin: 0px;padding: 0px;}</style>");
    var bftvn = '';
bftvn += "<"+"script type=\"text/javascript\">\n";
bftvn += "var file_url = \"//served-by.pixfuture.com/www/headerbid/library/\";\n";
bftvn += "var t = 3;\n";
bftvn += "var tout = 2000;\n";
bftvn += "var site_url = \"//served-by.pixfuture.com/www/headerbid/library/\";\n";
bftvn += "var org_site_url = \"//served-by.pixfuture.com/www/headerbid/library/\";\n";
bftvn += "var int = new Array();\n";
bftvn += "var pbjs = pbjs || {};\n";
bftvn += "pbjs.que = pbjs.que || [];\n";
bftvn += "var che = \"728\";\n";
bftvn += "var sz = [\"24880x728x90x4219x_ADSLOT1\"];\n";
bftvn += "var bz = [\"banner\"];\n";
bftvn += "int[0]={\"24880x728x90x4219x_ADSLOT1\":{\"url\":\"\",\"is_house\":1,\"cpm\":0,\"floor_price\":0,\"width\":\"728\",\"height\":\"90\",\"code\":\"4219\",\"zoneid\":\"24880\",\"adUnitCode\":\"24880x728x90x4219x_ADSLOT1\",\"type\":\"house\",\"third_share\":\"70\",\"int_share\":\"70\",\"passback\":\"<"+"script async src=\\\"https:\\/\\/pagead2.googlesyndication.com\\/pagead\\/js\\/adsbygoogle.js\\\"><"+"\\/script> <"+"!-- Display 728x90 --> <"+"ins class=\\\"adsbygoogle\\\" style=\\\"display:inline-block;width:728px;height:90px\\\" data-ad-client=\\\"ca-pub-3732773600888178\\\" data-ad-slot=\\\"1410653048\\\"><"+"\\/ins> <"+"script> (adsbygoogle = window.adsbygoogle || []).push({}); <"+"\\/script>\",\"campaignId\":null,\"bannerId\":null}};\n";
bftvn += "var eldxm = [\n";
bftvn += "/*header-bidding-bidders*/\n";
bftvn += "{\n";
bftvn += "code:\"24880x728x90x4219x_ADSLOT1\",\n";
bftvn += "mediaTypes: {banner: { sizes:[728,90]}},\n";
bftvn += "bids: [{bidder : \"conversant\",params: {\"site_id\": \"202603\"}},{bidder : \"aol\",params: {\"placement\": \"3344885\",\"network\": \"9834\"}},{bidder : \"appnexus\",params: {\"keywords\": { \"myKeyword\": \"education,icons,free,download,png,svg\",\"myOtherKeyword\": [\'education\',\'icons\',\'free\',\'download\',\'png\',\'svg\']},\"placementId\": 15106105}},{bidder : \"openx\",params: {\"customParams\": { \"myKeyword\": \"education,icons,free,download,png,svg\",\"myOtherKeyword\": [\'education\',\'icons\',\'free\',\'download\',\'png\',\'svg\']},\"delDomain\": \"pixfuture2-d.openx.net\",\"unit\": \"540580842\"}},{bidder : \"pulsepoint\",params: {\"cf\": \"728x90\",\"cp\": 561987,\"ct\": 686543}},{bidder : \"smartadserver\",params: {\"target\": \"education=education|icons=icons|free=free|download=download|png=png|svg=svg\",\"formatId\": 88674,\"pageId\": 1240155,\"siteId\": \"354470\"}},{bidder : \"pubmatic\",params: {\"dctr\": \"education=education|icons=icons|free=free|download=download|png=png|svg=svg\",\"adSlot\": \"2069654\",\"publisherId\": \"158127\",\"kadfloor\": \"0.1\"}},{bidder : \"33across\",params: {\"siteId\": \"azC7qard4r6OkMaKlId8sQ\",\"productId\": \"siab\"}},{bidder : \"synacormedia\",params: {\"seatId\": \"pixfuture\",\"placementId\": \"84884\",\"bidfloor\": 0.1}},{bidder : \"improvedigital\",params: {\"placementId\": 22292112,\"bidFloor\": 0.1}}]\n";
bftvn += "}];\n";
bftvn += "pbjs.que.push(function(){\n";
bftvn += "pbjs.setConfig({\n";
bftvn += "userSync: {\n";
bftvn += "filterSettings: {\n";
bftvn += "iframe: {\n";
bftvn += "bidders: \"*\",\n";
bftvn += "filter: \"include\"\n";
bftvn += "}\n";
bftvn += "},\n";
bftvn += "syncsPerBidder: 0,\n";
bftvn += "syncDelay: 1000\n";
bftvn += "},\n";
bftvn += "schain: {\n";
bftvn += "validation: \"strict\",\n";
bftvn += "config: {\n";
bftvn += "ver:\"1.0\",\n";
bftvn += "complete: 1,\n";
bftvn += "nodes: [\n";
bftvn += "{\n";
bftvn += "asi:\"pixfuture.com\",\n";
bftvn += "sid:\"4219\",\n";
bftvn += "hp:1\n";
bftvn += "}\n";
bftvn += "]\n";
bftvn += "}\n";
bftvn += "},\n";
bftvn += "consentManagement: {\n";
bftvn += "gdpr: {\n";
bftvn += "cmpApi: \"iab\",\n";
bftvn += "timeout: 100,\n";
bftvn += "allowAuctionWithoutConsent: true\n";
bftvn += "},\n";
bftvn += "usp: {\n";
bftvn += "timeout: 100 // US Privacy timeout 100ms\n";
bftvn += "}\n";
bftvn += "},pubcid: {expInterval: 525600}       })\n";
bftvn += "pbjs.requestBids({\n";
bftvn += "adUnits:eldxm,\n";
bftvn += "bidsBackHandler: function(bidResponses) {\n";
bftvn += "try {\n";
bftvn += "//console.log(dome(eldxm));\n";
bftvn += "dome(eldxm, false);\n";
bftvn += "} catch (e) {\n";
bftvn += "console.log(e);\n";
bftvn += "console.log(\"retry sending request!!!!!!!\");\n";
bftvn += "setTimeout(function(){\n";
bftvn += "dome(eldxm, false);\n";
bftvn += "}, 300);\n";
bftvn += "}\n";
bftvn += "},\n";
bftvn += "timeout: 2000,\n";
bftvn += "});\n";
bftvn += "});\n";
bftvn += "var zone_id         = 24880;\n";
bftvn += "function loadScript(url, callback) {\n";
bftvn += "var script = document.createElement(\"script\")\n";
bftvn += "script.type = \"text/javascript\";\n";
bftvn += "if (script.readyState) {\n";
bftvn += "script.onreadystatechange = function() {\n";
bftvn += "if (script.readyState == \"loaded\" || script.readyState == \"complete\") {\n";
bftvn += "script.onreadystatechange = null;\n";
bftvn += "callback()\n";
bftvn += "}\n";
bftvn += "}\n";
bftvn += "} else {\n";
bftvn += "script.onload = function() {\n";
bftvn += "callback()\n";
bftvn += "}\n";
bftvn += "}\n";
bftvn += "script.src = url;\n";
bftvn += "document.getElementsByTagName(\"head\")[0].appendChild(script)\n";
bftvn += "}\n";
bftvn += "<"+"/script>\n";
doc.write(bftvn);
doc.close();});